/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/users/{id}/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Change a user's password (self-service or admin reset) */
        put: operations["changePassword"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{id}/lock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Heartbeat/extend the edit lock you already hold */
        put: operations["heartbeat"];
        /**
         * Acquire the edit lock
         * @description 200 if acquired; 409 with holder info if already held by someone else
         */
        post: operations["acquire"];
        /** Release the edit lock (holder, or ADMIN/SUPER_ADMIN force-release) */
        delete: operations["release"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{id}/design-data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Replace a project's design data (requires edit access) */
        put: operations["updateDesignData"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List users (SUPER_ADMIN sees all, ADMIN sees their own organization) */
        get: operations["list"];
        put?: never;
        /** Create a user */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List projects visible to the current user */
        get: operations["list_1"];
        put?: never;
        /** Create a new project */
        post: operations["create_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List a project's sharing grants (owner only) */
        get: operations["list_2"];
        put?: never;
        /** Grant or update a user's access to a project (owner only) */
        post: operations["add"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List organizations */
        get: operations["list_3"];
        put?: never;
        /** Create an organization */
        post: operations["create_2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/calculations/ipr": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run an IPR (Inflow Performance Relationship) calculation using the Vogel or Fetkovich correlation */
        post: operations["calculateIpr"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate the refresh token and issue a new access token */
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log out and revoke the current refresh token */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log in with email and password */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a project by ID, including its design data */
        get: operations["getById"];
        put?: never;
        post?: never;
        /** Delete a project (soft delete, owner only) */
        delete: operations["delete"];
        options?: never;
        head?: never;
        /** Rename a project or change its visibility (owner only) */
        patch: operations["updateMetadata"];
        trace?: never;
    };
    "/api/v1/organizations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an organization by ID */
        get: operations["getById_1"];
        put?: never;
        post?: never;
        /** Delete an organization (only if it has no active users) */
        delete: operations["delete_1"];
        options?: never;
        head?: never;
        /** Rename an organization */
        patch: operations["rename"];
        trace?: never;
    };
    "/api/v1/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a user by ID */
        get: operations["getById_2"];
        put?: never;
        post?: never;
        /** Deactivate a user (soft delete, revokes active sessions) */
        delete: operations["delete_2"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tubings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List tubings */
        get: operations["list_4"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tubings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a tubing by id */
        get: operations["getById_3"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/casings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List casings */
        get: operations["list_5"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/casings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a casing by id */
        get: operations["getById_4"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the currently authenticated user */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{id}/members/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke a user's access to a project (owner only) */
        delete: operations["remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ChangePasswordRequest: {
            /** @description Required when changing your own password; ignored for an admin-initiated reset */
            currentPassword?: string;
            newPassword: string;
        };
        LockStatusResponse: {
            held?: boolean;
            mine?: boolean;
            /** Format: int64 */
            lockedByUserId?: number;
            lockedByName?: string;
            /** Format: date-time */
            lockedUntil?: string;
        };
        CompletionDto: {
            /**
             * Format: double
             * @description ft
             */
            lengthOfShots?: number;
            /**
             * Format: double
             * @description ft
             */
            averageShotDepth?: number;
            /**
             * Format: double
             * @description ft
             */
            pumpSettlementLength?: number;
            /**
             * Format: double
             * @description ft
             */
            pumpSettlementDepth?: number;
            /** Format: int32 */
            numberCasingPipes?: number;
            /**
             * Format: double
             * @description ft
             */
            casingUpperLength?: number;
            /**
             * Format: double
             * @description in
             */
            casingUpperOuterDiameter?: number;
            /**
             * Format: double
             * @description in
             */
            casingUpperInnerDiameter?: number;
            /**
             * Format: int32
             * @description Reference id into the casing catalog (modules:tubular)
             */
            casingUpperSelectionId?: number;
            /**
             * Format: double
             * @description ft
             */
            casingMiddleLength?: number;
            /**
             * Format: double
             * @description in
             */
            casingMiddleOuterDiameter?: number;
            /**
             * Format: double
             * @description in
             */
            casingMiddleInnerDiameter?: number;
            /**
             * Format: int32
             * @description Reference id into the casing catalog (modules:tubular)
             */
            casingMiddleSelectionId?: number;
            /**
             * Format: double
             * @description ft
             */
            casingBottomLength?: number;
            /**
             * Format: double
             * @description in
             */
            casingBottomOuterDiameter?: number;
            /**
             * Format: double
             * @description in
             */
            casingBottomInnerDiameter?: number;
            /**
             * Format: int32
             * @description Reference id into the casing catalog (modules:tubular)
             */
            casingBottomSelectionId?: number;
            /** Format: int32 */
            numberProductionTubings?: number;
            /**
             * Format: double
             * @description ft
             */
            tubingUpperLength?: number;
            /**
             * Format: double
             * @description in
             */
            tubingUpperOuterDiameter?: number;
            /**
             * Format: double
             * @description in
             */
            tubingUpperInnerDiameter?: number;
            /**
             * Format: int32
             * @description Reference id into the tubing catalog (modules:tubular)
             */
            tubingUpperSelectionId?: number;
            /**
             * Format: double
             * @description ft
             */
            tubingMiddleLength?: number;
            /**
             * Format: double
             * @description in
             */
            tubingMiddleOuterDiameter?: number;
            /**
             * Format: double
             * @description in
             */
            tubingMiddleInnerDiameter?: number;
            /**
             * Format: int32
             * @description Reference id into the tubing catalog (modules:tubular)
             */
            tubingMiddleSelectionId?: number;
            /**
             * Format: double
             * @description ft
             */
            tubingBottomLength?: number;
            /**
             * Format: double
             * @description in
             */
            tubingBottomOuterDiameter?: number;
            /**
             * Format: double
             * @description in
             */
            tubingBottomInnerDiameter?: number;
            /**
             * Format: int32
             * @description Reference id into the tubing catalog (modules:tubular)
             */
            tubingBottomSelectionId?: number;
        };
        DesignDataDto: {
            newProjectInfo?: components["schemas"]["StepDtoNewProjectInfoDto"];
            completion?: components["schemas"]["StepDtoCompletionDto"];
            directionalSurvey?: components["schemas"]["StepDtoListDirectionalSurveyRowDto"];
            fluids?: components["schemas"]["StepDtoFluidsDto"];
            ipr?: components["schemas"]["StepDtoIprDto"];
        };
        DesignPoint: {
            /**
             * Format: double
             * @description Flowing BHP required to produce desiredOilRate, in psia
             */
            requiredFlowingBottomholePressure?: number;
            /**
             * Format: double
             * @description Total liquid rate equivalent to desiredOilRate, in STB/d
             */
            totalFlowRate?: number;
            /**
             * Format: double
             * @description Oil rate at the design point in STB/d
             */
            oilFlowRate?: number;
            /**
             * Format: double
             * @description Water rate at the design point in STB/d
             */
            waterFlowRate?: number;
        };
        DirectionalSurveyRowDto: {
            /** Format: int32 */
            id?: number;
            /**
             * Format: double
             * @description Measured depth, ft
             */
            md?: number;
            /**
             * Format: double
             * @description True vertical depth, ft
             */
            tvd?: number;
            /**
             * Format: double
             * @description Horizontal displacement, ft
             */
            hd?: number;
            /**
             * Format: double
             * @description deg
             */
            angle?: number;
        };
        FluidsDto: {
            /**
             * Format: double
             * @description Injected fluid gravity, °API
             */
            oilGravityInjected?: number;
            /**
             * Format: double
             * @description psi
             */
            separatorPressure?: number;
            /**
             * Format: double
             * @description °F
             */
            separatorTemperature?: number;
            /**
             * Format: double
             * @description Gas-oil ratio, scf/stb
             */
            gor?: number;
            /**
             * Format: double
             * @description Produced fluid gravity, °API
             */
            oilGravity?: number;
            /**
             * Format: double
             * @description Specific gravity, gas
             */
            sgg?: number;
            /**
             * Format: double
             * @description Formation water salinity, ppm Cl⁻
             */
            salinity?: number;
            /**
             * Format: double
             * @description Specific gravity, injected water
             */
            sgw?: number;
            /**
             * Format: double
             * @description BSW, fraction 0-1
             */
            waterCut?: number;
            /**
             * Format: double
             * @description Pb, psi
             */
            bubblePointPressure?: number;
            /** @enum {string} */
            injectedFluidType?: "OIL" | "WATER";
            /** @enum {string} */
            gasSolubilityCorrelation?: "VELARDE_BLASINGAME" | "STANDING" | "VASQUEZ_BEGGS";
            /** @enum {string} */
            oilFvfCorrelation?: "VALKO_MCCAIN_SPIVEY" | "STANDING";
            /** @enum {string} */
            saturatedOilViscosityCorrelation?: "BEGGS_ROBINSON" | "CHEW_CONNALLY";
            /** @enum {string} */
            undersaturatedOilViscosityCorrelation?: "PETROSKY_FARSHAD" | "VASQUEZ_BEGGS";
            /** @enum {string} */
            deadOilViscosityCorrelation?: "RODA_V80_120" | "BEAL" | "GLASO";
            /** @enum {string} */
            waterFvfViscosityCorrelation?: "MCCAIN" | "MEEHAN";
            /** @enum {string} */
            gasViscosityCorrelation?: "LEE" | "CARR_KOBAYASHI";
            /** @enum {string} */
            gasCompressibilityCorrelation?: "ABOU_KASSEM" | "HALL_YARBOROUGH";
            /** @enum {string} */
            waterSurfaceTensionCorrelation?: "JENNINGS_NEWMAN";
            /** @enum {string} */
            oilSurfaceTensionCorrelation?: "ABDUL_MAJEED" | "BAKER_SWERDLOFF";
        };
        IprCurvePoint: {
            /**
             * Format: double
             * @description Flowing bottomhole pressure in psia, rounded to 2 decimals
             */
            flowingBottomholePressure?: number;
            /**
             * Format: double
             * @description Total flow rate in STB/d, rounded to 2 decimals
             */
            totalFlowRate?: number;
            /**
             * Format: double
             * @description Oil flow rate in STB/d, rounded to 2 decimals
             */
            oilFlowRate?: number;
            /**
             * Format: double
             * @description Water flow rate in STB/d, rounded to 2 decimals
             */
            waterFlowRate?: number;
        };
        IprDto: {
            /**
             * Format: double
             * @description °F
             */
            bottomholeTemperature?: number;
            /**
             * Format: double
             * @description °F
             */
            wellheadTemperature?: number;
            /**
             * Format: double
             * @description Ps, psi
             */
            reservoirPressure?: number;
            /**
             * Format: double
             * @description Pwf, psi
             */
            flowingBottomholePressure?: number;
            /**
             * Format: double
             * @description psi
             */
            pumpIntakePressure?: number;
            /**
             * Format: double
             * @description bfpd
             */
            testFlowRate?: number;
            /**
             * Format: double
             * @description bipd
             */
            maxInjectedVolume?: number;
            /**
             * Format: double
             * @description psi
             */
            maxInjectionPressure?: number;
            /**
             * Format: double
             * @description Qt/Qcavitación
             */
            jetMaxRatio?: number;
            /**
             * Format: double
             * @description %
             */
            jetMinEfficiency?: number;
            /**
             * Format: double
             * @description GPM/GPMmáx
             */
            pistonMaxRatio?: number;
            /**
             * Format: double
             * @description bfpd
             */
            designFlowRate?: number;
            /**
             * Format: double
             * @description psi
             */
            flowingWellheadPressure?: number;
            /**
             * Format: double
             * @description bipd
             */
            maxRefInjectionRate?: number;
            /**
             * Format: double
             * @description psi
             */
            maxInjectionPressureAdjusted?: number;
            /** @enum {string} */
            injectedFluidHydraulicCorrelation?: "DARCY_WEISBACH" | "HAZEN_WILLIAMS";
            /** @enum {string} */
            multiphaseFlowCorrelation?: "GRIFFITH" | "BEGGS_BRILL" | "HAGEDORN_BROWN";
            /** @description Last successful IPR calculation result, stored as-is for reload without recalculating */
            lastResult?: components["schemas"]["IprResultDto"];
            /**
             * @description Correlation used for lastResult
             * @enum {string}
             */
            lastCorrelation?: "VOGEL" | "FETKOVICH";
            /**
             * Format: int32
             * @description curvePointCount used for lastResult
             */
            lastCurvePointCount?: number;
        };
        IprResultDto: {
            /**
             * Format: double
             * @description Productivity index (J) in STB/d/psi
             */
            productivityIndex?: number;
            /**
             * Format: double
             * @description Total flow rate at the bubble point (qb) in STB/d
             */
            bubblePointFlowRate?: number;
            /**
             * Format: double
             * @description Absolute open flow potential (AOF) in STB/d
             */
            absoluteOpenFlow?: number;
            /**
             * Format: double
             * @description Flow rate at the model's internal operating point in STB/d
             */
            operatingPointFlowRate?: number;
            /**
             * Format: double
             * @description Flowing bottomhole pressure at the operating point in psia
             */
            operatingPointPressure?: number;
            /**
             * Format: double
             * @description Slope of the final linear segment beyond the operating point, in psi/(STB/d)
             */
            finalSegmentSlope?: number;
            /**
             * Format: double
             * @description Regressed Fetkovich exponent (n); null for VOGEL
             */
            fetkovichExponent?: number;
            /**
             * @description Correlation applied
             * @enum {string}
             */
            correlation?: "VOGEL" | "FETKOVICH";
            /** @description Points on the IPR curve, evenly spaced in total flow rate from 0 to absoluteOpenFlow; each value rounded to 2 decimals */
            curvePoints?: components["schemas"]["IprCurvePoint"][];
            /** @description Jet pump design point for desiredOilRate; null when desiredOilRate was not sent. Values are full precision (not rounded) */
            designPoint?: components["schemas"]["DesignPoint"];
        };
        NewProjectInfoDto: {
            newProjectName?: string;
            companyName?: string;
            location?: string;
            sandType?: string;
            analystName?: string;
            oilField?: string;
            wellName?: string;
            /** Format: date */
            date?: string;
            commentaries?: string;
            wellType?: string;
        };
        StepDtoCompletionDto: {
            dataEntered?: boolean;
            data?: components["schemas"]["CompletionDto"];
        };
        StepDtoFluidsDto: {
            dataEntered?: boolean;
            data?: components["schemas"]["FluidsDto"];
        };
        StepDtoIprDto: {
            dataEntered?: boolean;
            data?: components["schemas"]["IprDto"];
        };
        StepDtoListDirectionalSurveyRowDto: {
            dataEntered?: boolean;
            data?: components["schemas"]["DirectionalSurveyRowDto"][];
        };
        StepDtoNewProjectInfoDto: {
            dataEntered?: boolean;
            data?: components["schemas"]["NewProjectInfoDto"];
        };
        UpdateDesignDataRequest: {
            designData: components["schemas"]["DesignDataDto"];
            /**
             * Format: int64
             * @description The version this edit was based on; a 409 VERSION_CONFLICT means someone else saved first
             */
            version: number;
        };
        ProjectResponse: {
            /** Format: int64 */
            id?: number;
            name?: string;
            /** Format: int64 */
            ownerId?: number;
            ownerName?: string;
            /** @enum {string} */
            visibility?: "PRIVATE" | "ORGANIZATION";
            /** @enum {string} */
            myPermission?: "OWNER" | "EDITOR" | "VIEWER" | "NONE";
            designData?: components["schemas"]["DesignDataDto"];
            /**
             * Format: int64
             * @description Pass back on the next design-data update to detect concurrent edits
             */
            version?: number;
            /**
             * Format: int64
             * @description Null unless another user currently holds the edit lock
             */
            lockedByUserId?: number;
            /** @description Null unless another user currently holds the edit lock */
            lockedByName?: string;
            /**
             * Format: date-time
             * @description Null unless another user currently holds the edit lock
             */
            lockedUntil?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        CreateUserRequest: {
            /** Format: email */
            email: string;
            password: string;
            firstName: string;
            lastName: string;
            /** @enum {string} */
            role: "SUPER_ADMIN" | "ADMIN" | "MEMBER";
            /**
             * Format: int64
             * @description Required only when the caller is SUPER_ADMIN creating a non-SUPER_ADMIN user; an ADMIN's own organization is used automatically otherwise
             */
            organizationId?: number;
        };
        UserResponse: {
            /** Format: int64 */
            id?: number;
            email?: string;
            firstName?: string;
            lastName?: string;
            /** @enum {string} */
            role?: "SUPER_ADMIN" | "ADMIN" | "MEMBER";
            /**
             * Format: int64
             * @description Null only for SUPER_ADMIN
             */
            organizationId?: number;
            /** @description Null only for SUPER_ADMIN */
            organizationName?: string;
        };
        CreateProjectRequest: {
            name: string;
            /** @enum {string} */
            visibility?: "PRIVATE" | "ORGANIZATION";
            designData?: components["schemas"]["DesignDataDto"];
        };
        AddProjectMemberRequest: {
            /** Format: int64 */
            userId: number;
            /** @enum {string} */
            role: "VIEWER" | "EDITOR";
        };
        ProjectMemberResponse: {
            /** Format: int64 */
            userId?: number;
            name?: string;
            email?: string;
            /** @enum {string} */
            role?: "VIEWER" | "EDITOR";
        };
        CreateOrganizationRequest: {
            name: string;
        };
        OrganizationResponse: {
            /** Format: int64 */
            id?: number;
            name?: string;
        };
        IprCalculationRequest: {
            /**
             * Format: double
             * @description Reservoir (static) pressure in psia
             */
            reservoirPressure: number;
            /**
             * Format: double
             * @description Bubble point pressure in psia
             */
            bubblePointPressure: number;
            /**
             * Format: double
             * @description Water cut as a fraction (0-1)
             */
            waterCut: number;
            /**
             * @description IPR correlation to apply
             * @enum {string}
             */
            correlation: "VOGEL" | "FETKOVICH";
            /** @description Well test points; VOGEL requires exactly 1, FETKOVICH requires at least 2 */
            testPoints: components["schemas"]["TestPoint"][];
            /**
             * Format: int32
             * @description Curve points to generate; engine defaults to 101
             */
            curvePointCount?: number;
            /**
             * Format: double
             * @description Desired oil rate in STB/d for the jet pump design point; optional. Requires waterCut < 1 and must not exceed the well's maximum achievable oil rate (enforced upstream)
             */
            desiredOilRate?: number;
        };
        TestPoint: {
            /**
             * Format: double
             * @description Well-test total flow rate in STB/d
             */
            flowRate: number;
            /**
             * Format: double
             * @description Well-test flowing bottomhole pressure in psia
             */
            flowingBottomholePressure: number;
        };
        IprCalculationResponse: {
            /**
             * Format: double
             * @description Productivity index (J) in STB/d/psi
             */
            productivityIndex?: number;
            /**
             * Format: double
             * @description Total flow rate at the bubble point (qb) in STB/d
             */
            bubblePointFlowRate?: number;
            /**
             * Format: double
             * @description Absolute open flow potential (AOF) in STB/d
             */
            absoluteOpenFlow?: number;
            /**
             * Format: double
             * @description Flow rate at the model's internal operating point in STB/d
             */
            operatingPointFlowRate?: number;
            /**
             * Format: double
             * @description Flowing bottomhole pressure at the operating point in psia
             */
            operatingPointPressure?: number;
            /**
             * Format: double
             * @description Slope of the final linear segment beyond the operating point, in psi/(STB/d)
             */
            finalSegmentSlope?: number;
            /**
             * Format: double
             * @description Regressed Fetkovich exponent (n); null for VOGEL
             */
            fetkovichExponent?: number;
            /**
             * @description Correlation applied
             * @enum {string}
             */
            correlation?: "VOGEL" | "FETKOVICH";
            /** @description Points on the IPR curve, evenly spaced in total flow rate from 0 to absoluteOpenFlow; each value rounded to 2 decimals */
            curvePoints?: components["schemas"]["IprCurvePoint"][];
            /** @description Jet pump design point for desiredOilRate; null when desiredOilRate was not sent. Values are full precision (not rounded) */
            designPoint?: components["schemas"]["DesignPoint"];
        };
        AuthResponse: {
            accessToken?: string;
            user?: components["schemas"]["UserResponse"];
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        UpdateProjectMetadataRequest: {
            name: string;
            /** @enum {string} */
            visibility: "PRIVATE" | "ORGANIZATION";
        };
        UpdateOrganizationRequest: {
            name: string;
        };
        PageResponseUserResponse: {
            content?: components["schemas"]["UserResponse"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
        };
        TubingResponse: {
            /** Format: int64 */
            id?: number;
            /** @description Outer diameter in inches */
            outerDiameter?: number;
            /** @description Inner diameter in inches */
            innerDiameter?: number;
            /** @description Drift diameter in inches */
            driftDiameter?: number;
            /** @description Nominal weight in lbs/ft */
            nominalWeight?: string;
            grade?: string;
            /**
             * Format: int32
             * @description Collapse pressure in psi
             */
            collapsePressure?: number;
            /**
             * Format: int32
             * @description Minimum internal yield pressure in psi
             */
            minimumInternalYieldPressure?: number;
        };
        PageResponseProjectSummaryResponse: {
            content?: components["schemas"]["ProjectSummaryResponse"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
        };
        ProjectSummaryResponse: {
            /** Format: int64 */
            id?: number;
            name?: string;
            /** Format: int64 */
            ownerId?: number;
            ownerName?: string;
            /** @enum {string} */
            visibility?: "PRIVATE" | "ORGANIZATION";
            /** @enum {string} */
            myPermission?: "OWNER" | "EDITOR" | "VIEWER" | "NONE";
            /**
             * Format: int64
             * @description Null unless another user currently holds the edit lock
             */
            lockedByUserId?: number;
            /** @description Null unless another user currently holds the edit lock */
            lockedByName?: string;
            /**
             * Format: date-time
             * @description Null unless another user currently holds the edit lock
             */
            lockedUntil?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        PageResponseOrganizationResponse: {
            content?: components["schemas"]["OrganizationResponse"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
        };
        CasingResponse: {
            /** Format: int64 */
            id?: number;
            /** @description Outer diameter in inches */
            outerDiameter?: number;
            /** @description Inner diameter in inches */
            innerDiameter?: number;
            /** @description Drift diameter in inches */
            driftDiameter?: number;
            /** @description Nominal weight in lbs/ft */
            nominalWeight?: string;
            grade?: string;
            /**
             * Format: int32
             * @description Collapse pressure in psi
             */
            collapsePressure?: number;
            /**
             * Format: int32
             * @description Minimum internal yield pressure in psi
             */
            minimumInternalYieldPressure?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    heartbeat: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LockStatusResponse"];
                };
            };
        };
    };
    acquire: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LockStatusResponse"];
                };
            };
        };
    };
    release: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateDesignData: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateDesignDataRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProjectResponse"];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseUserResponse"];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    list_1: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
                q?: string;
                sort?: string;
                scope?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseProjectSummaryResponse"];
                };
            };
        };
    };
    create_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProjectRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProjectResponse"];
                };
            };
        };
    };
    list_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProjectMemberResponse"][];
                };
            };
        };
    };
    add: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddProjectMemberRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProjectMemberResponse"];
                };
            };
        };
    };
    list_3: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseOrganizationResponse"];
                };
            };
        };
    };
    create_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrganizationRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OrganizationResponse"];
                };
            };
        };
    };
    calculateIpr: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IprCalculationRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["IprCalculationResponse"];
                };
            };
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                refresh_token?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuthResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                refresh_token?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuthResponse"];
                };
            };
        };
    };
    getById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProjectResponse"];
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateMetadata: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProjectMetadataRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProjectResponse"];
                };
            };
        };
    };
    getById_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OrganizationResponse"];
                };
            };
        };
    };
    delete_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    rename: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateOrganizationRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OrganizationResponse"];
                };
            };
        };
    };
    getById_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    delete_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_4: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TubingResponse"][];
                };
            };
        };
    };
    getById_3: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TubingResponse"];
                };
            };
        };
    };
    list_5: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CasingResponse"][];
                };
            };
        };
    };
    getById_4: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CasingResponse"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                userId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
